# Site settings
title: No Third Party
analytics: UA-59753785-1
baseurl: "" 
url: "https://nothirdparty.com"
markdown: kramdown

# Build settings
permalink: /:categories/:title
excerpt_separator: <!--more--> 

gems:
  - jekyll-redirect-from

# colors
colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#00364c" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
